### ISSUE TITLE
4378

### ISSUE THREAD

**Issue by NatashaYao** [holistic-video-understanding/Mini-HVU#2]
I have 2 questions,
1.I analysed the tags of the training data, it has 2550 classes not 4378，could you told me why?
2. Could you please add the category of each class?

**Comment by alidiba67** [comment]
@NatashaYao Hi, 1.This version is Mini-HVU and 4378 classes belongs to full HVU dataset which will be released by the end of Oct.
2. sure, it will be released by the main dataset.

**Comment by NatashaYao** [comment]
Now it's November, the full dataset should be available
